//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProRecruit
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateExperience
    {
        public int Id { get; set; }
        public string PositionHeld { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string UserId { get; set; }
        public string Description { get; set; }
        public string OrganizationName { get; set; }
    
        public virtual Candidate Candidate { get; set; }
    }
}
