//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProRecruit
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Candidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidate()
        {
            this.CandidateCertifications = new HashSet<CandidateCertification>();
            this.CandidateExperiences = new HashSet<CandidateExperience>();
            this.CandidateJobs = new HashSet<CandidateJob>();
            this.CandidateLanguages = new HashSet<CandidateLanguage>();
            this.CandidateProjects = new HashSet<CandidateProject>();
            this.CandidateQualifications = new HashSet<CandidateQualification>();
            this.CandidateSkills = new HashSet<CandidateSkill>();
        }

        [Display(Name = "First Name")]
        public string FirstName { get; set; }
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        public string Email { get; set; }
        [Display(Name = "Date Of Birth")]
        public System.DateTime DateOfBirth { get; set; }
        public string Gender { get; set; }
        [Display(Name = "Marital Status")]
        public string MaritalStatus { get; set; }
        public string Nationality { get; set; }
        public string City { get; set; }
        [Display(Name = "CNIC / SSN")]
        public string CNIC { get; set; }
        [Display(Name = "Postal Address")]
        public string CurrentAddress { get; set; }
        [Display(Name = "Contact Number")]
        public string Contact { get; set; }
        public string Industry { get; set; }
        [Display(Name = "Functional Area")]
        public string FunctionalArea { get; set; }
        [Display(Name = "Current Salary")]
        public string CurrentSalary { get; set; }
        [Display(Name = "Expected Salary")]
        public string ExpectedSalary { get; set; }
        [Display(Name = "Career Level")]
        public string CarreerLevel { get; set; }
        public string UserId { get; set; }
        public string Summary { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateCertification> CandidateCertifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateExperience> CandidateExperiences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateJob> CandidateJobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateLanguage> CandidateLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateProject> CandidateProjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateQualification> CandidateQualifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateSkill> CandidateSkills { get; set; }
    }
}
