//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProRecruit
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CandidateQualification
    {
        public int Id { get; set; }
        [Display(Name = "Qualification")]
        public int QualificationId { get; set; }
        public string Institute { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public string DegreeLevel { get; set; }
        public string DegreeType { get; set; }
        public string Degreetitle { get; set; }
        public string MajorSubjects { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Institution { get; set; }
        public string CompletionYear { get; set; }
        public string ResultType { get; set; }
        public string TotalGPA { get; set; }
        public string TotalGrade { get; set; }
        public string TotalPercentage { get; set; }
        public string YourGPA { get; set; }
        public string UserId { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual Qualification Qualification { get; set; }
    }
}
