//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProRecruit
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class CandidateSkill
    {
        public int Id { get; set; }
        [Display(Name = "Skill")]
        public int SkillId { get; set; }
        [Display(Name = "Experience with skill")]
        public string ExperienceWithSkill { get; set; }
        public string UserId { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
