//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProRecruit
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateCertification
    {
        public int Id { get; set; }
        public string CertificationTitle { get; set; }
        public string CertificationDescription { get; set; }
        public string UserId { get; set; }
    
        public virtual Candidate Candidate { get; set; }
    }
}
