//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProRecruit
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobQualification
    {
        public int Id { get; set; }
        public int JobId { get; set; }
        public Nullable<int> QualificationId { get; set; }
        public string DegreeLevel { get; set; }
        public string DegreeType { get; set; }
        public string DegreeTitle { get; set; }
        public string MajorSubject { get; set; }
        public string Location { get; set; }
        public string Institution { get; set; }
        public string CompletionYear { get; set; }
        public string ResultType { get; set; }
        public string TotalGPA { get; set; }
        public string TotalPercentage { get; set; }
        public string TotalGrade { get; set; }
        public string YourGPA { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual Qualification Qualification { get; set; }
    }
}
