//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProRecruit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Organization()
        {
            this.Jobs = new HashSet<Job>();
        }
    
        public string UserId { get; set; }
        public string Name { get; set; }
        public string Industry { get; set; }
        public string ContactPerson { get; set; }
        public string Phonenumber { get; set; }
        public string Fax { get; set; }
        public string NoOfEmployee { get; set; }
        public string OperatingSince { get; set; }
        public string StockSymbol { get; set; }
        public string CompanyLogo { get; set; }
        public string PostedJobs { get; set; }
        public string Email { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job> Jobs { get; set; }
    }
}
